[profile.release]
codegen-units = 1
lto = true
strip = true

[workspace]
members = [
  "intouch2",
  "intouch2-mqtt",
]
resolver = "2"

[workspace.dependencies]
rand = "0.8"
serde = "1.0"
strum = { version = "0.25", features = ["derive"] }
thiserror = "2.0"
